### ISSUE TITLE
Please where is the vendor's folder

### ISSUE THREAD

**Issue by InspiredPrynce** [tjlytle/laravel-hotline#2]
I cant really do anything without the vendors folder...
Any help?

`λ php artisan serve

Warning: require(C:\wamp\www\laravel-hotline-master\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\laravel-hotline-master\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\wamp\www\laravel-hotline-master\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\wamp\www\laravel-hotline-master\bootstrap\autoload.php on line 17`

**Comment by tjlytle** [comment]
Before you can use the example app, you'll need to do a `composer install` to pull in all the dependencies. You can find out more about composer here: https://getcomposer.org/
